<a href="https://colab.research.google.com/github/RPAD676Spring2025/lab-3-sai-hemanth-kalidindi/blob/main/Lab3_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Lab 3: Analyzing Data in Python**

# RPAD 676: Data Science for the Public Good

## Author:
## Date:

## Instructions
In this assignment, you will conduct your own analysis using the provided dataset. Follow the prompts in each section and write the necessary Python code to complete the tasks.

**Tasks:**
- Load and explore the dataset
- Perform basic data cleaning (handling missing values, etc.)
- Generate descriptive statistics
- Create at least one meaningful visualization
- Summarize key insights from your analysis

Remember to document your thought process in markdown cells throughout the notebook.

In [13]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [15]:
import pandas as pd

# Replace with the correct file path inside your Google Drive
file_path = "/content/drive/My Drive/digital_services_data (1).csv"

# Load the dataset
data = pd.read_csv(file_path)

# Display the first few rows
print(data.head())


   user_id  TimeTaken  UserSatisfaction  Age  DisabilityStatus  \
0        2        919                 4   38                 0   
1        9        759                10   78                 0   
2       13        853                 8   45                 0   
3       15        503                 4   66                 0   
4       25        857                 7   69                 0   

   DigitalLiteracy  Gender EmploymentStatus EducationLevel InternetAccess  \
0                5  Female          Retired   Some College      Broadband   
1                5    Male         Employed    High School      Broadband   
2                3  Female       Unemployed       Bachelor      Broadband   
3                3    Male          Student       Bachelor      Broadband   
4                1  Female         Employed   Some College    Mobile Data   

   ErrorRates  RequestedHelp  SatisfactionOtherServices  WillingnessFutureUse  \
0           1              0                          6    

In [17]:
# Display the first few rows
data.head()

user_id  TimeTaken  UserSatisfaction  Age  DisabilityStatus  \
0        2        919                 4   38                 0   
1        9        759                10   78                 0   
2       13        853                 8   45                 0   
3       15        503                 4   66                 0   
4       25        857                 7   69                 0   

   DigitalLiteracy  Gender EmploymentStatus EducationLevel InternetAccess  \
0                5  Female          Retired   Some College      Broadband   
1                5    Male         Employed    High School      Broadband   
2                3  Female       Unemployed       Bachelor      Broadband   
3                3    Male          Student       Bachelor      Broadband   
4                1  Female         Employed   Some College    Mobile Data   

   ErrorRates  RequestedHelp  SatisfactionOtherServices  WillingnessFutureUse  \
0           1              0                          6                    10   
1           1              0                          3                     8   
2           2              0                          6                    10   
3           1              0                          2                     1   
4           4              0                          3                     1   

   ReceivesSocialServices                                   Agency  
0                       0  Department of Health and Human Services  
1                       0              Department of Public Safety  
2                       0                  Department of Education  
3                       0              Department of Public Safety  
4                       0                  Department of Education

In [18]:


# Display the first few rows
print(data.head())

# Check for missing values
print(data.isnull().sum())

# Display basic information about the dataset
print(data.info())


   user_id  TimeTaken  UserSatisfaction  Age  DisabilityStatus  \
0        2        919                 4   38                 0   
1        9        759                10   78                 0   
2       13        853                 8   45                 0   
3       15        503                 4   66                 0   
4       25        857                 7   69                 0   

   DigitalLiteracy  Gender EmploymentStatus EducationLevel InternetAccess  \
0                5  Female          Retired   Some College      Broadband   
1                5    Male         Employed    High School      Broadband   
2                3  Female       Unemployed       Bachelor      Broadband   
3                3    Male          Student       Bachelor      Broadband   
4                1  Female         Employed   Some College    Mobile Data   

   ErrorRates  RequestedHelp  SatisfactionOtherServices  WillingnessFutureUse  \
0           1              0                          6    

In [19]:
# Display the first few rows
print(data.head())

# Check column names
print(data.columns)

# Get general information about the dataset
print(data.info())

# Check for missing values
print(data.isnull().sum())


   user_id  TimeTaken  UserSatisfaction  Age  DisabilityStatus  \
0        2        919                 4   38                 0   
1        9        759                10   78                 0   
2       13        853                 8   45                 0   
3       15        503                 4   66                 0   
4       25        857                 7   69                 0   

   DigitalLiteracy  Gender EmploymentStatus EducationLevel InternetAccess  \
0                5  Female          Retired   Some College      Broadband   
1                5    Male         Employed    High School      Broadband   
2                3  Female       Unemployed       Bachelor      Broadband   
3                3    Male          Student       Bachelor      Broadband   
4                1  Female         Employed   Some College    Mobile Data   

   ErrorRates  RequestedHelp  SatisfactionOtherServices  WillingnessFutureUse  \
0           1              0                          6    

In [20]:
# Drop rows with missing values
data_cleaned = data.dropna()

# Verify missing values are removed
print(data_cleaned.isnull().sum())


user_id                      0
TimeTaken                    0
UserSatisfaction             0
Age                          0
DisabilityStatus             0
DigitalLiteracy              0
Gender                       0
EmploymentStatus             0
EducationLevel               0
InternetAccess               0
ErrorRates                   0
RequestedHelp                0
SatisfactionOtherServices    0
WillingnessFutureUse         0
ReceivesSocialServices       0
Agency                       0
dtype: int64


## Descriptive Statistics

Compute and interpret basic statistics for the dataset:
- Mean, median, mode
- Standard deviation, min, max
- Any other relevant metrics

_Write your code below:_

In [23]:
from IPython.display import display

# Display descriptive statistics
display(desc_stats)


user_id    TimeTaken  UserSatisfaction          Age  \
count  1000.000000  1000.000000       1000.000000  1000.000000   
mean    500.500000  1059.025000          4.946000    49.039000   
std     288.819436   344.668741          2.901293    17.891998   
min       1.000000     0.000000          1.000000    18.000000   
25%     250.750000   830.500000          2.000000    34.000000   
50%     500.500000  1064.000000          5.000000    50.000000   
75%     750.250000  1274.000000          7.000000    64.000000   
max    1000.000000  2136.000000         10.000000    79.000000   

       DisabilityStatus  DigitalLiteracy   ErrorRates  RequestedHelp  \
count       1000.000000      1000.000000  1000.000000    1000.000000   
mean           0.153000         3.053000     2.387000       0.287000   
std            0.360168         1.397907     2.384726       0.452588   
min            0.000000         1.000000     0.000000       0.000000   
25%            0.000000         2.000000     1.000000       0.000000   
50%            0.000000         3.000000     2.000000       0.000000   
75%            0.000000         4.000000     4.000000       1.000000   
max            1.000000         5.000000    22.000000       1.000000   

       SatisfactionOtherServices  WillingnessFutureUse  ReceivesSocialServices  
count                1000.000000           1000.000000             1000.000000  
mean                    5.606000              5.765000                0.616000  
std                     2.873852              3.050095                0.486601  
min                     1.000000              1.000000                0.000000  
25%                     3.000000              3.000000                0.000000  
50%                     6.000000              6.000000                1.000000  
75%                     8.000000              8.000000                1.000000  
max                    10.000000             10.000000                1.000000

## Data Visualization

Create at least one visualization that highlights an interesting aspect of the dataset. You may use bar plots, histograms, scatter plots, or other relevant charts.

_Write your code below:_

In [24]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))
sns.histplot(data_cleaned['UserSatisfaction'], bins=10, kde=True)
plt.title('Distribution of User Satisfaction Scores')
plt.xlabel('User Satisfaction')
plt.ylabel('Frequency')
plt.show()


## Inferential Statistics

### T-Tests
Compare means across two groups using the t-test. Calculate the means, conduct the t-test, and summarize the findings and what they say about the relationship between the variables.

_Write your code below:_

In [25]:
from scipy import stats

# Splitting data into two groups
broadband_users = data_cleaned[data_cleaned['InternetAccess'] == 'Broadband']['UserSatisfaction']
mobile_data_users = data_cleaned[data_cleaned['InternetAccess'] == 'Mobile Data']['UserSatisfaction']

# Performing an independent t-test
t_stat, p_value = stats.ttest_ind(broadband_users, mobile_data_users, equal_var=False)

print(f"T-Test Results: t-statistic = {t_stat:.3f}, p-value = {p_value:.3f}")


T-Test Results: t-statistic = -0.447, p-value = 0.655


1. P-value (0.655) is much greater than 0.05

This means we fail to reject the null hypothesis (no significant difference in user satisfaction between broadband and mobile data users).
In simple terms, Internet Access Type (Broadband vs. Mobile Data) does not significantly affect user satisfaction.

2. T-statistic (-0.447) is close to 0

A small t-value suggests that the difference between the two groups is minimal.

### ANOVA
Compare means across two groups using the t-test. Calculate the means, conduct the t-test, and summarize the findings and what they say about the relationship between the variables.

_Write your code below:_

In [26]:
# Grouping data by Education Level
education_groups = [group['UserSatisfaction'] for name, group in data_cleaned.groupby('EducationLevel')]

# Conducting ANOVA test
anova_stat, anova_p = stats.f_oneway(*education_groups)

print(f"ANOVA Results: F-statistic = {anova_stat:.3f}, p-value = {anova_p:.3f}")


ANOVA Results: F-statistic = 0.125, p-value = 0.945


1.P-value (0.945) is much greater than 0.05

This means we fail to reject the null hypothesis (there is no significant difference in user satisfaction across different education levels).
In simple terms, education level does not significantly affect user satisfaction.

2.F-statistic (0.125) is very small

A small F-value indicates that the variability between education groups is not significantly greater than the variability within each group.


## Key Insights

Summarize your findings in a short paragraph. What patterns or trends did you observe? Were there any surprises in the data? How might these insights be useful?

_Write your response below:_

Key Insights from the Analysis

1.User Satisfaction is not significantly influenced by Internet Access Type

The T-Test (p-value = 0.655) shows no significant difference in satisfaction scores between broadband and mobile data users.
This suggests that internet quality or type is not a major factor affecting satisfaction with digital services.
Education Level does not significantly impact User Satisfaction

2. TheANOVA test (p-value = 0.945) indicates that education level has no meaningful effect on satisfaction scores.
This was surprising, as one might expect higher education levels to correlate with higher satisfaction in digital services.

3.Potential Influencing Factors

Since Internet Access and Education Level are not significant factors, other characteristics like Digital Literacy, Age, Employment Status, or Time Taken may have a stronger impact on user satisfaction.
Further correlation analysis or regression modeling could help identify key drivers of satisfaction.